on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      envPAT:
        required: true

jobs:
  call-workflow-passing-data:
    uses: t-maoshengye/test-reusable-workflows/.github/workflows/reusable-workflow.yml@dev
    with:
      username: ye
    secrets:
      envPAT: ${{ secrets.envPAT }}